### ISSUE TITLE
Ergonomics props are passed down to children through ...rest

### ISSUE THREAD

**Issue by quarkboy** [kodyl/react-flexr#11] opened 2016-08-02 10:19 UTC
This gives lots of warnings in React 0.15:

`warning.js:44 Warning: Unknown prop `desk` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

Also, perhaps this is by design, but when resizing manually by dragging the window, the ergonomics breakpoints aren't triggered until I reload the page at the new size... related?

**Comment by danieljuhl** [comment] 2016-08-02 12:06
Ergonomics shouldn't be passed ... I'll fix that as soon as possible.

But it is by design, that the app is not re-rendered, as it could cause problems, you will have to trigger the re-render yourself, if you want it.

**Comment by danieljuhl** [comment] 2016-08-02 12:07
I will try and provide an example on how to trigger the re-render.

**Comment by danieljuhl** [comment] 2016-08-22 20:22
A new version of `react-flexr` is coming tomorrow, fixing this issue. I'll try to update the docs for re-render in this week too.

**Comment by danieljuhl** [comment] 2016-08-23 06:44
Should be fixed in `react-flexr@2.1.0`

**Closed by danieljuhl** 2016-08-23 06:44 UTC

**Comment by danieljuhl** [comment] 2016-08-23 06:46
@quarkboy there is a little information in the README, look at `optimizedResize`. We are planning a HoC though, which change a prop for the component, if case of a new breakpoint.
