### ISSUE TITLE
warning  'Cell' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by julescopeland** [kodyl/react-flexr#15] opened 2016-11-18 16:53 UTC
Hi,

I'm relatively new to React, so forgive me if this is a dumb question...

When I break apart my components into separate files, and only use the top level `Grid` in one file and the `Cell` in another, the code won't work unless I import both at the top.

Webpack then fires off a load of warnings in the console about `warning  'Cell' is defined but never used  no-unused-vars`.

It's not breaking anything, but it's a bit annoying when you have similar arrangements across lots of files. Short of switching off the warnings (the rest of which are quite useful), is there a 'right' way of fixing this?

Thanks.

**Comment by danieljuhl** [comment] 2016-11-21 12:33
@julescopeland I have not been able to reproduce this. Can you provide a minimal test case.

**Comment by danieljuhl** [comment] 2017-09-28 10:59
Closing as I couldn't reproduce

**Closed by danieljuhl** 2017-09-28 10:59 UTC
