### ISSUE TITLE
Grid hAlign doesn't appear to have an effect

### ISSUE THREAD

**Issue by delaneyj** [kodyl/react-flexr#1] opened 2015-06-12 19:25 UTC
Cell stuff works but so far can't get Grid's flexCells, hAlign, align to have any effect when set.

This is in Chrome on a windows 8.1 box.

**Comment by chriskjaer** [comment] 2015-06-15 17:35
flexCells only have an effect when the cell elements inside the grid have different heights.

As to the hAlign: you will only be able to horizontally center cells inside the grid if they all have widths. 
E.g. this modified snippet taken from the example folder will horizontally center the containing cells:
```javascript
        <Grid hAlign='center'>
          <Cell size='4/12'>
            <div>
              horizontally centered.
            </div>
          </Cell>
          <Cell size='4/12'>
            <div>
              horizontally centered.
            </div>
          </Cell>
        </Grid>

```

**Comment by delaneyj** [comment] 2015-06-15 23:35
I did try this with a single cell `size='6/12'` with no effect

**Comment by chriskjaer** [comment] 2015-06-16 06:47
I'm having a hard time debugging this, since the code in the example folder is working as intended. Besides that we use flexr in production and haven't had any issues so far.

I would to help out though, do you have any code that I can review? 

You could also try manually centering with css to rule out that you don't have any interferring styles. The containing element should have.
```
justify-content: center;
display: flex;
```
and then the centered item inside needs to have a width smaller than the container.

**Comment by chriskjaer** [comment] 2015-06-17 13:45
I'll close this for now. If there's any new in this case, I'll consider reopening the issue.

**Closed by chriskjaer** 2015-06-17 13:45 UTC

**Comment by brad-decker** [comment] 2015-07-16 18:46
@chriskjaer Supplying a size for every cell does indeed fix the alignment issue of hAlign not applying, but for some reason anytime i give a size to every cell (5 cells at 1/5 size) the fifth cell wraps to the next row.

**Comment by brad-decker** [comment] 2015-07-16 18:54
Ignore me, obviously if having 1/5 * 5 sized cells would be a full width container and hAlign wouldn't be necessary.
